name: MessagePlugin
version: '${project.version}'
main: me.jumpccy.messageplugin.MessagePlugin
api-version: 1.17
authors: [ jjump88 ]
description: msg plugin
commands:
  msg:
    description: send message to a player
    usage: /msg (player) (message)
    aliases: [w, message]
